### ISSUE TITLE
PointContrast for Outdoor Data

### ISSUE THREAD

**Issue by YilmazKadir** [valeoai/ALSO#2]
Do not we need different views of the same pointcloud to train PointContrast? How did you pretrain NuScenes and SemanticKITTI datasets with PointContrast approach? Did you just use the static parts of the scene?

**Comment by aboulch** [comment]
Yes, for PointContrast, you need two views of the same point cloud.
For SemanticKITTI, we compare to the models trained by the authors of SegContrast.
For NuScenes, we retrained point contrast with the same parameters as in https://github.com/valeoai/SLidR.

In PointContrast, when creating the pairs of points, there is an implicit filtering of the moving objects: if the points have moved two much, the matching cannot be done (threshold on the distance). Therefore, PointContrast handles the moving objects out-of-the-box. We do not filter the scenes.
